-- ========================================================
-- SCRIPT DE MIGRATION DE LA BASE DE DONNÉES SUPABASE
-- Coaching VIP
-- ========================================================

-- 1. CORRECTION DE L'ERREUR : Colonnes manquantes dans workout_logs
ALTER TABLE workout_logs
ADD COLUMN IF NOT EXISTS actual_performances JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS completed_sets JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS student_comment TEXT,
ADD COLUMN IF NOT EXISTS duration_seconds INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'completed';

-- 2. DÉFINITION COMPLÈTE DU SCHÉMA DU PROJET (Au cas où d'autres tables manquent)

-- Table PROFILES
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  role TEXT DEFAULT 'client',
  first_name TEXT,
  last_name TEXT,
  full_name TEXT,
  phone TEXT,
  birth_date DATE,
  height NUMERIC,
  weight NUMERIC,
  coach_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  specialties TEXT,
  certifications TEXT,
  years_experience INTEGER,
  bio TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table STUDENT_COACHES (Relation Many-to-Many entre Élèves et Coaches)
CREATE TABLE IF NOT EXISTS student_coaches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  coach_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(student_id, coach_id)
);

-- Table PROGRAMS
CREATE TABLE IF NOT EXISTS programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  coach_note TEXT,
  coach_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  student_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table EXERCISES
CREATE TABLE IF NOT EXISTS exercises (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT REFERENCES programs(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  sets INTEGER DEFAULT 4,
  reps TEXT DEFAULT '10-12',
  target_weight TEXT DEFAULT '20kg',
  order_index INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table WORKOUT_LOGS
CREATE TABLE IF NOT EXISTS workout_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT REFERENCES programs(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  duration_seconds INTEGER DEFAULT 0,
  completed_sets JSONB DEFAULT '{}'::jsonb,
  actual_performances JSONB DEFAULT '{}'::jsonb,
  student_comment TEXT,
  status TEXT DEFAULT 'completed',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
